pipeline {
    agent any
    environment {
        // Define the SonarQube server to use
        SONARQUBE_URL = 'http://localhost:9000'
    }
    stages {
        stage('Build') {
            steps {
                // Comandos de construcción
                sh 'mvn clean install'
            }
        }
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('http://localhost:9000') {
                    // Ejecutar el análisis de SonarQube
                    sh 'mvn sonar:sonar'
                }
            }
        }
        stage('Quality Gate') {
            steps {
                script {
                    // Verificar la calidad del código
                    def qg = waitForQualityGate()
                    if (qg.status != 'OK') {
                        error "Pipeline aborted due to quality gate failure: ${qg.status}"
                    }
                }
            }
        }
    }
}